name: Android Build
on:
  push:
    branches: [ "master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Gradle cache
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build the project
      run: ./gradlew assembleDebug
